lib/elixir_stream_web/router.ex
defmodule ElixirStreamWeb.Router do
  use ElixirStreamWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug ElixirStreamWeb.GuardianPipeline
    plug :put_root_layout, {ElixirStreamWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :require_admin do
    plug :is_admin
  end

  pipeline :robots do
    plug :accepts, ~w[json txt xml webmanifest]
  end

  scope "/", ElixirStreamWeb, log: false do
    pipe_through [:robots]

    get "/robots.txt", RobotController, :robots
    get "/rss.xml", RobotController, :rss
    get "/site.webmanifest", RobotController, :site_webmanifest
    get "/browserconfig.xml", RobotController, :browserconfig
  end

  scope "/auth", ElixirStreamWeb do
    pipe_through [:browser]
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/", ElixirStreamWeb do
    pipe_through :browser

    live "/", PageLive, :index

    get "/about", PageController, :about

    get "/logout", AuthController, :delete
    delete "/logout", AuthController, :delete
    live "/profile", ProfileLive, :edit

    live "/tips", TipLive, :index
    live "/tips/new", TipLive, :new
    live "/tips/:id", TipLive, :show
    live "/tips/:id/edit", TipLive, :edit
  end

  scope "/admin", as: :admin do
    pipe_through [:browser, :require_admin]

    live_dashboard "/dashboard",
      metrics: ElixirStreamWeb.Telemetry,
      ecto_repos: [ElixirStream.Repo]
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  defp is_admin(conn, _opts) do
    user = Guardian.Plug.current_resource(conn)

    if ElixirStream.Accounts.admin?(user) do
      conn
    else
      conn
      |> redirect(to: "/")
      |> halt()
    end
  end
end

lib/petal_web/router.ex
defmodule PetalWeb.Router do
  use PetalWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PetalWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PetalWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PetalWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PetalWeb.Telemetry
    end
  end
end

lib/elixir_stream_web/views/layout_view.ex
defmodule ElixirStreamWeb.LayoutView do
  use ElixirStreamWeb, :view
  import ElixirStream.Accounts, only: [admin?: 1]

  @doc """
  A shim for Phoenix.HTML.Link.link, but adding a class if currently on the page and picking the best LiveView link
  helper (live_patch vs live_redirect vs link). Integrated with AlpineJS.
  """
  def active_link(conn, route, text, opts)

  def active_link(conn, route, opts, do: contents) when is_list(opts) do
    active_link(conn, route, contents, opts)
  end

  def active_link(%Phoenix.LiveView.Socket{} = socket, route, text, opts) do
    to = opts |> Keyword.fetch!(:to) |> String.split("?") |> hd()
    destination_info = Phoenix.Router.route_info(socket.router, "GET", to, socket.endpoint.host)

    liveview_opts = [
      "@click": "$dispatch('navigate', '#{route}')",
      ":class": "{'active': currentRoute === '#{route}', '': currentRoute !== '#{route}'}"
    ]

    with current_liveview <- socket.view,
         %{phoenix_live_view: {^current_liveview, _action}} <- destination_info do
      Phoenix.LiveView.Helpers.live_patch(text, opts ++ liveview_opts)
    else
      %{phoenix_live_view: _} ->
        Phoenix.LiveView.Helpers.live_redirect(text, opts ++ liveview_opts)

      _ ->
        Phoenix.HTML.Link.link(text, opts)
    end
  end

  def active_link(%Plug.Conn{} = conn, route, text, opts) do
    to = Keyword.fetch!(opts, :to)

    destination_info =
      Phoenix.Router.route_info(conn.private[:phoenix_router], "GET", to, conn.host)

    liveview_opts = [
      "@click": "$dispatch('navigate', '#{route}')",
      ":class": "{'active': currentRoute === '#{route}', '': currentRoute !== '#{route}'}"
    ]

    with {current_liveview, _opts} <- conn.private[:phoenix_live_view],
         %{phoenix_live_view: {^current_liveview, _action}} <- destination_info do
      Phoenix.LiveView.Helpers.live_patch(text, opts ++ liveview_opts)
    else
      %{phoenix_live_view: _} ->
        Phoenix.LiveView.Helpers.live_redirect(text, opts ++ liveview_opts)

      _ ->
        Phoenix.HTML.Link.link(text, opts)
    end
  end

  def current_alpine_route(%Phoenix.LiveView.Socket{} = socket, live_action) do
    route =
      socket.router.__routes__()
      |> Enum.find(&({socket.view, live_action} == &1.metadata[:phoenix_live_view]))

    "/" <> path_info = route.path
    String.replace(path_info, "/", "-")
  end

  def current_alpine_route(%Plug.Conn{} = conn) do
    Enum.join(conn.path_info || ["/"], "-")
  end
end

lib/elixir_stream_web/templates/layout/_footer.html.leex
<%# _footer.html.leex template %>

<div class="border-t-4 border-brand-500">
  <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
    <div class="flex justify-center md:order-2 block print:hidden">
      <!-- <select class="dark:border-gray-800 border-gray-200 focus:ring-gray-500 focus:border-brand-500 ml-6 py-1 pl-2 pr-4 border-transparent bg-transparent text-gray-500 sm:text-sm rounded-md"
              x-data="themeChooser()"
              x-init="$watch('currentTheme', updateTheme)"
              x-model="currentTheme">
        <option disabled>Site theme</option>
        <template x-for="theme in colorThemes" :key="theme">
          <option :value="theme" x-text="theme" :selected="currentTheme === theme"></option>
        </template>
      </select> -->
      <%= link to: Routes.page_path(@conn, :about), title: "About", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">About</span>
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      <% end %>

      <%= outbound_link to: "https://twitter.com/elixirstream", title: "Twitter", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Twitter</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
        </svg>
      <% end %>
      <%= outbound_link to: "https://github.com/elixirstream", title: "GitHub", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      <% end %>
      <%= link to: Routes.robot_path(@conn, :rss), title: "RSS Feed", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">RSS Feed</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M5 3a1 1 0 000 2c5.523 0 10 4.477 10 10a1 1 0 102 0C17 8.373 11.627 3 5 3z"></path>
          <path d="M4 9a1 1 0 011-1 7 7 0 017 7 1 1 0 11-2 0 5 5 0 00-5-5 1 1 0 01-1-1zM3 15a2 2 0 114 0 2 2 0 01-4 0z"></path>
        </svg>
      <% end %>
      <%= outbound_link to: "https://plausible.io/elixirstream.dev", title: "Plausible", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Analytics</span>
        <svg viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
          <path fill-rule="evenodd" d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.707a1 1 0 00-1.414-1.414L10 9.586 8.707 8.293a1 1 0 00-1.414 0l-2 2a1 1 0 101.414 1.414L8 10.414l1.293 1.293a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
        </svg>
      <% end %>
    </div>

    <div class="mt-8 md:mt-0 md:order-1">
      <p class="text-center text-base leading-6 text-gray-400">
      &copy; 2021 Zest Creative, LLC<span class="hidden print:inline"> elixirstream.dev</span>
      </p>
    </div>
  </div>
</div>

lib/elixir_stream_web/templates/layout/_header.html.leex
<%# _header.html.l eex template %>
<head>
  <meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <% seo = %ElixirStreamWeb.Seo.Generic{} %>
  <meta name="description" content="<%= seo.description %>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0, shrink-to-fit=no"/>
  <meta name="msapplication-TileColor" content="#9428ec">
  <meta name="theme-color" content="#270642">
  <link rel="canonical" href="https://elixirstream.dev<%= Phoenix.Controller.current_path(@conn) %>" />
  <link rel="apple-touch-icon" sizes="180x180" type="image/png" href="<%= Routes.static_path(@conn, "/images/apple-touch-icon-180x180.png") %>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicon-16x16.png") %>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicon-32x32.png") %>">
  <link rel="manifest" href="<%= Routes.robot_path(@conn, :site_webmanifest) %>" %>
  <link rel="mask-icon" href="<%= Routes.static_path(@conn, "/images/safari-pinned-tab.svg") %>" color="#9428EC">
  <link rel="canonical" href="https://elixirstream.dev<%= Phoenix.Controller.current_path(@conn) %>" />
  <%= csrf_meta_tag() %>
  <%= live_title_tag assigns[:page_title] || "Home", suffix: " · Elixir Stream" %>
  <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  <%= if Application.get_env(:elixir_stream, :app_env) == :prod do %>
    <script async defer data-domain="elixirstream.dev" src="https://stats.elixirstream.dev/js/index.js"></script>
  <% end %>

  <script>
    if (localStorage.theme === "dark" || (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
      document.documentElement.classList.add("dark")
    } else {
      document.documentElement.classList.remove("dark")
    }
  </script>
</head>

lib/elixir_stream_web/templates/layout/_nav.html.leex
<%# _nav.html.leex template %>
<!-- Top Nav -->
<header x-data="{'profileOpen': false, 'mobileNav': false, 'currentRoute': '<%= current_alpine_route(@socket, @live_action) %>'}"
        x-bind:class="{'fixed inset-0 z-40 overflow-y-auto': mobileNav}"
        class="bg-white shadow-sm lg:static lg:overflow-y-visible"
        x-on:navigate.window="currentRoute = $event.detail; mobileNav = false">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="relative flex justify-between xl:grid xl:grid-cols-12 lg:gap-8">
      <div class="flex md:absolute md:left-0 md:inset-y-0 lg:static xl:col-span-2">
        <div class="flex-shrink-0 flex items-center">
          <%= live_redirect to: "/", class: "flex items-center justify-center h-16 w-16 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-brand-500 md:w-20" do %>
            <%= img_tag Routes.static_path(@socket, "/images/logo.svg"), class: "block h-10 w-auto", alt: "Elixir Stream" %>
            <span class="ml-2 leading-none text-brand-800" style="font-weight: 600; font-family: 'Fira Sans'">elixir stream</span>
          <% end %>
        </div>
      </div>
      <div class="min-w-0 flex-1 md:px-16 lg:px-0 xl:col-span-6">
        <div class="flex items-center px-6 py-4 md:max-w-3xl md:mx-auto lg:max-w-none lg:mx-0 xl:px-0">
          <div class="w-full">
            <label for="search" class="sr-only">Search</label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 pl-3 flex items-center">
                <!-- Heroicon name: solid/search -->
                <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                </svg>
              </div>
              <%= f = form_for @search_changeset, "#", phx_change: "search", as: "search", id: "search-form", onsubmit: "return false;" %>
              <%= search_input f, :q, [
                phx_debounce: "250",
                class: "block w-full bg-white border border-gray-300 rounded-md py-2 pl-10 pr-3 text-sm placeholder-gray-500 focus:outline-none focus:text-gray-900 focus:placeholder-gray-400 focus:ring-1 focus:ring-brand-500 focus:border-brand-500 sm:text-sm",
                maxlength: "75",
                placeholder: gettext("Search tips"),
                id: "search",
                x_ref: "searchField",
                "x-on:keydown.window.slash": "if ($event.target.tagName !== 'INPUT' && $event.target.tagName !== 'TEXTAREA') { $event.preventDefault(); $refs.searchField.focus() }"]
              %>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="flex items-center md:absolute md:right-0 md:inset-y-0 lg:hidden">
        <!-- Mobile menu button -->
        <button @click="mobileNav = !mobileNav" type="button" class="-mx-2 rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-brand-500" aria-expanded="false">
          <span class="sr-only">Open menu</span>
          <!-- Heroicon name: outline/menu -->
          <svg x-bind:class="{'hidden': mobileNav, 'block': !mobileNav}" class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!-- Heroicon name: outline/x -->
          <svg x-bind:class="{'block': mobileNav, 'hidden': !mobileNav}" class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:items-center lg:justify-end xl:col-span-4">
        <%= if @current_user.id do %>
          <!-- Profile dropdown -->
          <div class="flex-shrink-0 relative ml-5">
            <div>
              <button x-on:click="profileOpen = !profileOpen" type="button" class="bg-white rounded-full flex focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-500" id="user-menu" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <img class="h-8 w-8 rounded-full" src="<%= @current_user.avatar %>" alt="">
              </button>
            </div>

            <!-- User menu -->
            <div
              @click.away="profileOpen = false"
              x-show="profileOpen"
              x-cloak
              x-transition:enter="transition ease-out duration-100"
              x-transition:enter-start="transform opacity-0 scale-95"
              x-transition:enter-end="transform opacity-100 scale-100"
              x-transition:leave="transition ease-in duration-75"
              x-transition:leave-start="transform opacity-100 scale-100"
              x-transition:leave-end="transform opacity-0 scale-95"
              class="origin-top-right absolute z-10 right-0 mt-2 w-48 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 py-1 focus:outline-none divide-y-2 divide-gray-300"
              role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
              <div>
                <%= live_redirect "Your Profile",
                  to: Routes.profile_path(@socket, :edit),
                  class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100",
                  role: "menuitem" %>
                <%= link "Sign out",
                  to: Routes.auth_path(@socket, :delete),
                  class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100",
                  role: "menuitem" %>
              </div>
              <%= if admin?(@current_user) do %>
                <div>
                  <%= link "Dashboard",
                    to: Routes.live_dashboard_path(@socket, :home),
                    class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100",
                    role: "menuitem" %>
                </div>
              <% end %>
            </div>
          </div>
        <% else %>
          <%= link to: Routes.auth_path(@socket, :request, "github"), class: "inline-flex items-center px-3 py-2 border border-transparent shadow-sm text-sm leading-4 font-medium rounded-md text-white bg-black hover:bg-brand-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-500" do %>
            <svg class="text-white -ml-0.5 mr-2 h-4 w-4" fill="currentColor" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <title>GitHub icon</title>
              <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>
            </svg>
            Login
          <% end %>
        <% end %>

        <%= active_link @socket, "tips/new", "New Tip", to: Routes.tip_path(@socket, :new), class: "ml-6 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-brand-600 hover:bg-brand-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-500" %>
      </div>
    </div>
  </div>

  <!-- Mobile menu -->
  <nav x-cloak x-show="mobileNav" class="lg:hidden" aria-label="Global">
    <div class="max-w-3xl mx-auto px-2 pt-2 pb-3 space-y-1 sm:px-4">
      <%= if !@current_user.id do %>
        <div class="border-b border-gray-200 pt-4 pb-3">
          <%= link to: Routes.auth_path(@socket, :request, "github"), class: "menu-link ml-2" do %>
            <svg class="text-black inline -ml-0.5 mr-2 h-4 w-4" fill="currentColor" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <title>GitHub icon</title>
              <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>
            </svg>
            Login
          <% end %>
        </div>
      <% end %>
      <%= active_link @socket, "tips-new", "New Tip", to: Routes.tip_path(@socket, :new), "x-on:click": "mobileNav = false", class: "menu-link" %>
      <%= active_link @socket, "tips", "Latest Tips", to: Routes.tip_path(@socket, :index, %{"sort" => "latest"}), "x-on:click": "mobileNav = false", class: "menu-link" %>
      <%= active_link @socket, "tips-popular", "Popular Tips", to: Routes.tip_path(@socket, :index, %{"sort" => "popular"}), "x-on:click": "mobileNav = false", class: "menu-link" %>
    </div>
    <%= if @current_user.id do %>
      <div class="border-t border-gray-200 pt-4 pb-3">
        <div class="max-w-3xl mx-auto px-4 flex items-center sm:px-6">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="<%= @current_user.avatar %>" alt="">
          </div>
          <div class="ml-3">
            <div class="text-base font-medium text-gray-800"><%= @current_user.name %></div>
            <div class="text-sm font-medium text-gray-500"><%= @current_user.username %></div>
          </div>
        </div>
        <div class="mt-3 max-w-3xl mx-auto px-2 space-y-1 sm:px-4">
          <%= live_redirect "Your Profile", to: Routes.profile_path(@socket, :edit), class: "block rounded-md py-2 px-3 text-base font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-900", "x-on:click": "mobileNav = false" %>
          <%= link "Sign out", to: Routes.auth_path(@socket, :delete), class: "block rounded-md py-2 px-3 text-base font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-900" %>

          <%= if admin?(@current_user) do %>
            <%= link "Dashboard",
              to: Routes.live_dashboard_path(@socket, :home),
              class: "block rounded-md py-2 px-3 text-base font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-900" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </nav>
</header>

lib/elixir_stream_web/templates/layout/app.html.eex
<main class="min-w-0 flex-1 border-t border-gray-200 lg:flex">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/elixir_stream_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <%= render "_header.html", assigns %>
  <body class="antialiased" data-version="<%= Application.spec(:elixir_stream, :vsn) %>">
    <a class="skip-main" href="#main">Skip to main content</a>
    <%= @inner_content %>
    <%= render "_footer.html", assigns %>
  </body>
</html>